public enum Token {
    ME, MUD, STONE, GEM, EXIT, WALL, BRICKS, PATH, EXPLOSION, SLIME, SWAPLING, BLOCKLING, XLING,
    GHOSTLING, FIRE, NORTHTHING, EASTTHING, SOUTHTHING, WESTTHING, POT, SIEVE, SAND
}